### ISSUE TITLE
Vyper template?

### ISSUE THREAD

**Issue by samajammin** [scaffold-eth/scaffold-eth#130]
Hey frands 😄 

Just got this question from a member in our ethereum.org Discord:

> hi! new to vyper, I would like to clone a very simple dapp to have a look at the full stack of an ethereum dapp from back end (write compile and deploy a simple contract) to an internet site as a front end facing the internet. where to find an example to have a look at all the details, to better understand all the components involved in the pipeline , and how they interact? (if this is not the right place to ask, where should i ask?)

I don't see any `vyper` branches on this repo. Have you considered adding a Vyper template?

Thanks!

**Comment by codenamejason** [comment]
We could definitely create a vyper branch if your interested.

**Comment by codenamejason** [comment]
@samajammin would you be interested in working on this?

**Comment by samajammin** [comment]
Unfortunately I don't have the capacity to work on this. I sense Vyper has also been losing steam since I opened this. Feel free to close this out if you folks don't have the time.

**Comment by emilianobonassi** [comment]
Revamping this with #824.

Added the vyper equivalent of YourContract.sol and required dependencies for compiling with success.

Users can decide to work with Solidity, Vyper or both. As scaffold utils we can provide example for both.
