### ISSUE TITLE
Consider reducing # of dependencies & package size

### ISSUE THREAD

**Issue by paulmillr** [scaffold-eth/scaffold-eth#152]
Nice app! Love the simplicity. This is how most apps should look and feel.

`5.4M Apr  2 20:15 2.b733adae.chunk.js`

What if I told you any 20 bytes of those 5400000 bytes could contain a backdoor that would steal user funds? You're using quite a few dependencies there.

My initial suggestion would be to switch to [micro-eth-signer](https://github.com/paulmillr/micro-eth-signer) — which abstracts out addresses and transactions. It uses noble-secp256k1 instead of indutny/elliptic, which alone could reduce size by a lot.

**Comment by captnseagraves** [comment]
@paulmillr Thanks for the suggestion! Any chance you would be willing to submit a PR?

**Comment by paulmillr** [comment]
Sure. Would you accept it?

**Comment by azf20** [comment]
Is the idea to replace ethers.js?

**Comment by paulmillr** [comment]
Nope. The idea is to provide a tiny library for those who don't need full ethers.js functionality.

**Comment by azf20** [comment]
OK. scaffold-eth uses ethers quite extensively for reading & writing, would there be a size benefit if ethers was still being used for reading?

**Comment by paulmillr** [comment]
For reading what?

**Comment by codenamejason** [comment]
reading the blockchain...
