### ISSUE TITLE
nft-auction YourCollectibles not working?

### ISSUE THREAD

**Issue by CapuM** [scaffold-eth/scaffold-eth#182]
Once the auction is over YourCollectibles page should display the nft if the user owns it..

**Comment by pabloruiz55** [comment]
I can see that the stuff that fetched the YourCollectibles data was commented out in this commit: https://github.com/austintgriffith/scaffold-eth/commit/2a33554df58f0921066059c906d28d6ad084397e#diff-a7537a962908e0277100acf2a73555c0b82075f18978a904eb34930d9a174d49R192

@ironsoul0 do you recall why that was taken out? I tried uncommenting those lines but there's also some stuff missing in the contract preventing it from fully functioning.

**Comment by captnseagraves** [comment]
@CapuM @pabloruiz55 Is this issue still relevant? Looking to groom backlog.
