### ISSUE TITLE
⚡ Zapper X 🏗 scaffold-eth

### ISSUE THREAD

**Issue by pabloruiz55** [scaffold-eth/scaffold-eth#217]
branch 1: read only dashboard
branch 2: zap in zap out

From @viraj124 : would need their api and we can probably use any popular zap contract and embed it in scaffold

**Comment by codenamejason** [comment]
Do they have a graph?

**Comment by codenamejason** [comment]
Anyone want to work on this? This would make a great advanced tutorial.
