### ISSUE TITLE
Create a Yarn Create <Starter-kit> for Scaffold-eth

### ISSUE THREAD

**Issue by pabloruiz55** [scaffold-eth/scaffold-eth#238]
The idea would be that someone can install the package on their computer and then run `yarn create scaffold-eth` and it will create a ready-to-go folder.

Additionally, would be cool if you could do `yarn create scaffold-eth --template=simple-nft-sample to get the folder created with that template.

https://classic.yarnpkg.com/en/docs/cli/create/

**Comment by hexedout** [comment]
Might be a bit late but I actually made this a few weeks ago if you want to [check it out](https://www.npmjs.com/package/create-scaffold-eth), it basically just clones either scaffold-eth or one of the branches listed on SpeedRunEthereum
