### ISSUE TITLE
Improve Transactor error handling

### ISSUE THREAD

**Issue by azf20** [scaffold-eth/scaffold-eth#241]
As per https://github.com/austintgriffith/scaffold-eth/pull/237, error responses differ by network & wallet. The current solution mostly shows the raw error. Find a way to parse a prettier reason across networks for Metamask & the Burner:

- [ ] Hardhat
- [ ] Kovan
- [ ] Rinkeby
- [ ] Ropsten
- [ ] Mainnet
- [ ] xDai
- [ ] Polygon

_This may require investigating how this is handled by ethers.js_

**Comment by pabloruiz55** [comment]
Ideally we solve this issue, though from reading online forums I wouldn't get my hopes up.

In any case, given that local Hardhat is giving the results ok, I'd say that's good enough. In a production app you shouldn't get to the point where the user sees these errors, but rather validate them on the front-end so they almost never get there. I.E: if submitting an empty "purpose" reverts, then validate the form input so it can not be submitted empty.

**Comment by codenamejason** [comment]
@azf20 can I get someone to work on this? Are you interested in working on it?
