### ISSUE TITLE
Sample Project Request: Multisig

### ISSUE THREAD

**Issue by pabloruiz55** [scaffold-eth/scaffold-eth#244]
Use the solidity code from: https://solidity-by-example.org/app/multi-sig-wallet/

We have such a branch already (https://github.com/austintgriffith/scaffold-eth/tree/multi-sig-wallet) but it's very very outdated and doesn't have a custom UI either.

**Comment by austintgriffith** [comment]
This is the most up-to-date branch of a multi-sig, but it's signature based: https://github.com/austintgriffith/scaffold-eth/tree/meta-multi-sig

Building a multi-sig-wallet in 🏗 scaffold-eth is a fantastic place for anyone wanting to build idea!

**Comment by codenamejason** [comment]
moved to scaffold-eth-challenges branch
