### ISSUE TITLE
Adding deploy support for Skynet

### ISSUE THREAD

**Issue by dghelm** [scaffold-eth/scaffold-eth#323]
I'd be interested in contributing a PR to add Skynet alongside IPFS, AWS and surge as a deployment option in the template.

[Skynet](https://siasky.net/) is a decentralized, open storage protocol that enables hosting decentralized web apps and front-ends. It is architectured so that pinning and hosting happen at different parts of the network. It's quite performant, requires nothing for access beyond a web browser, and enables rich applications that can use both mutable and immutable data that can be persisted off-chain to Skynet.

The deployment would work similarly to IPFS/IPNS, where the upload would have a specific, changing skylink for the immutable deployment and a consistent "resolver skylink" across subsequent deployments. Skylinks are also natively supported by ENS in both MetaMask and `eth.link`.

**Comment by codenamejason** [comment]
This is a great idea for a new branch that others can use as a starting point to interact and use Skynet with Scaffold-Eth.
