### ISSUE TITLE
Unhandled Rejection (Error): missing response

### ISSUE THREAD

**Issue by dcsan** [scaffold-eth/scaffold-eth#352]
I see this all the time with this project, after leaving my app open for a couple of minutes.
maybe instability in the testnet, but it causes the whole app to red screen of death.

is there anyway to catch this error from blowing up the front-end ?

I'm not sure exactly where it's from looking through the stack trace even

> missing response (requestBody="{\"method\":\"eth_getBalance\",\"params\":

![image](https://user-images.githubusercontent.com/514002/131269164-09c8b717-7cee-40d6-86b4-f93a9c7fd7ca.png)

![image](https://user-images.githubusercontent.com/514002/131269203-604faada-8ae6-426f-8a1c-e488d0f4fbee.png)

somewhere deep in base_provider?

![image](https://user-images.githubusercontent.com/514002/131269222-8bf78548-62b2-47e6-aa60-81b638467a45.png)

**Comment by codenamejason** [comment]
Did you update your Infura id in the constants.js file?

**Comment by john--** [comment]
Make sure you've run all of the commands, including the one to start hardhat (the "chain" one).

**Comment by codenamejason** [comment]
This is an rpc out of requests error that needs to be handled
