### ISSUE TITLE
Create "Production Mode" switch

### ISSUE THREAD

**Issue by captnseagraves** [scaffold-eth/scaffold-eth#361]
The "Production Mode" switch should disable or remove certain features in the repo the are unnecessary for production, such as the burner wallet in the upper right hand corner of the window. 

Eng grooming needed. Not enough detail. Likely need to be broken down into smaller tickets.

**Comment by StErMi** [comment]
The "production mode" and many other things that are at the moment hardcoded into code should rely on `.env` variables. For example, the network used by the frontend, the debug mode, the supported chains, and so on. 

We should add as soon as possible check out the [Dotenv documentation](https://github.com/motdotla/dotenv) for this.

For the react package we can follow the [Adding Custom Environment Variables](https://create-react-app.dev/docs/adding-custom-environment-variables/) documentation. 

For hardhat the same thing, the `infura project_id` should be in a `.env` and the current `network`.
