### ISSUE TITLE
Transition scaffold-eth ecosystem repos to scaffold-eth github org

### ISSUE THREAD

**Issue by captnseagraves** [scaffold-eth/scaffold-eth#362]
Transfer repos according to these docs: https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/transferring-a-repository

Repos to be transferred: 
1. Scaffold-eth
2. Eth-hooks
3. Eth-components
4. Eth-services
5. ...?

**Comment by codenamejason** [comment]
Scaffold-Eth 🏗  has been moved to an organization.
