### ISSUE TITLE
Prune Branches

### ISSUE THREAD

**Issue by captnseagraves** [scaffold-eth/scaffold-eth#366]
Examine, rate, and prune branches in Scaffold-eth repo. We want to organize repos based on quality, spin out stand-alone branches into their own repos, and cultivate high-quality branches and documentation into new challenges and tutorials for the challenge course. 

We should look to only create new repos once we have transferred existing scaffold-eth ecosystem repos to the scaffold-eth github org.

**Comment by codenamejason** [comment]
Created a google sheet doc to organize this. https://docs.google.com/spreadsheets/d/1Cv5QhtgHzpxLsvy3GJIW7KjgWq4IMXY1iFoSCg3Me8U/edit?usp=sharing
