### ISSUE TITLE
Implement BuidlGuidl streams on L2 so buidlers don't have to pay $$$ fees to receive payment

### ISSUE THREAD

**Issue by captnseagraves** [scaffold-eth/scaffold-eth#368]

**Comment by codenamejason** [comment]
What about having streams on Polygon or Fantom, the bridges are solid and tx's are dirt cheap.

**Comment by azf20** [comment]
I think Arbitrum could be a good option, though might be worth investigating some gas optimisation to the contract to make mainnet deployment cheaper

**Comment by brendanboyle87** [comment]
Is deployment cost of the contract the issue? Or do you mean look at reducing the cost of the work link transaction?

**Comment by ShravanSunder** [comment]
the problem with arbritrum is the withdrawal period.

**Comment by codenamejason** [comment]
I am not a fan of waiting a week.

**Comment by brendanboyle87** [comment]
I agree its not great but I think it depends on what you plan to use it for. Some people may be willing to wait if it means getting the most out of their stream. Also I would hope at some point there would be enough l2 activity that people aren't immediately thinking about bridging it back. If you want instant you can use Hop Protocol https://hop.exchange/ (for a fee but still may be cheaper overall). I'm going to prove out a stream on Arbitrum and then look at potentially finding a way to give people the option of where they want their stream on the main UI.

**Comment by ShravanSunder** [comment]
i'll probably investigate this when zksync v2 with evm compatibility comes out

**Comment by codenamejason** [comment]
I would prefer Polygon honestly for cheap tx and you can bridge back and forth to ETH easily.
