### ISSUE TITLE
solidity-coverage returning error

### ISSUE THREAD

**Issue by marceljay** [scaffold-eth/scaffold-eth#375]
After installing the plugin via `yarn add solidity-coverage`

and adding `require("solidity-coverage");` according to the [docs](https://hardhat.org/plugins/solidity-coverage.html)

I get this error on the current scaffold-eth master `616ac8017` when running

```
└─$ npx hardhat coverage

Version
=======
> solidity-coverage: v0.7.17

Instrumenting for coverage...
=============================

> YourContract.sol

Compilation:
============

Compiling 2 files with 0.8.4
Compilation finished successfully
Error in plugin solidity-coverage: TypeError: Cannot read property 'match' of undefined

For more info run Hardhat with --show-stack-traces
```

## How to reproduce
```
git clone https://github.com/austintgriffith/scaffold-eth.git
```
```
cd scaffold-eth
```
```
yarn
```
```
cd packages/hardhat
```
```
yarn add solidity-coverage
```
```
npx hardhat coverage
```

Sys info:
```
OS: Ubuntu 20.04 focal
Kernel: x86_64 Linux 5.11.0-27-generic

─$ yarn -v
1.22.10
```

yarn lock: https://gist.github.com/marceljay/134733311bbbbef210c6b2d332dd7ebd

**Comment by codenamejason** [comment]
can you show your code please

**Comment by marceljay** [comment]
`require("solidity-coverage");` 
It's the scaffold-eth master branch. Easy to reproduce. Should I post the yarn.lock?

**Comment by codenamejason** [comment]
No, that's good.

**Comment by aspiers** [comment]
It seems that this is a hardhat issue:

https://github.com/sc-forks/solidity-coverage/issues/622

So I suggest closing this.
