### ISSUE TITLE
Yarn Toolkit Install Build Error on Ubuntu 21.04

### ISSUE THREAD

**Issue by gokulsan** [scaffold-eth/scaffold-eth#378]
Hello Scaffold Team,

I am trying to do YARN installation of Scaffold ETH on Ubuntu 21.04. Request for help to address this issue.

yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...

warning Pattern ["@apollo/client@latest"] is trying to unpack in the same destination "/home/semiott/.cache/yarn/v6/npm-@apollo-client-3.3.21-2862baa4e1ced8c5e89ebe6fc52877fc64a726aa-integrity/node_modules/@apollo/client" as pattern 

["@apollo/client@^3.3.21"]. This could result in non-deterministic behavior, skipping.
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/hardhat > @nomiclabs/hardhat-waffle@2.0.1" has incorrect peer dependency "@nomiclabs/hardhat-ethers@^2.0.0".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/hardhat > hardhat-deploy@0.9.0" has unmet peer dependency "@ethersproject/hardware-wallets@^5.0.14".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/hardhat > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-import@^2.22.1".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/hardhat > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.4.1".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/hardhat > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-react@^7.21.5".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/hardhat > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/hardhat > eslint-plugin-prettier@3.4.0" has unmet peer dependency "prettier@>=1.13.0".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > @testing-library/user-event@12.8.3" has incorrect peer dependency "@testing-library/dom@>=7.21.4".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > @uniswap/sdk@3.0.3" has unmet peer dependency "@ethersproject/address@^5.0.0-beta".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > @uniswap/sdk@3.0.3" has unmet peer dependency "@ethersproject/contracts@^5.0.0-beta".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > @uniswap/sdk@3.0.3" has unmet peer dependency "@ethersproject/networks@^5.0.0-beta".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > @uniswap/sdk@3.0.3" has unmet peer dependency "@ethersproject/providers@^5.0.0-beta".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > @uniswap/sdk@3.0.3" has unmet peer dependency "@ethersproject/solidity@^5.0.0-beta".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > arb-ts@0.0.18" has incorrect peer dependency "ethers@~5.0.24".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > eth-hooks@1.1.2" has unmet peer dependency "@ethersproject/address@^5.0.1".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > eth-hooks@1.1.2" has unmet peer dependency "@ethersproject/bignumber@^5.0.1".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > eth-hooks@1.1.2" has unmet peer dependency "@ethersproject/constants@^5.0.1".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > eth-hooks@1.1.2" has unmet peer dependency "@ethersproject/contracts@^5.0.1".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > eth-hooks@1.1.2" has unmet peer dependency "@ethersproject/providers@^5.0.2".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > eth-hooks@1.1.2" has unmet peer dependency "@ethersproject/units@^5.0.1".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > eth-hooks@1.1.2" has incorrect peer dependency "react@^16.9.0".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > graphiql@1.4.2" has incorrect peer dependency "graphql@>= v14.5.0 <= 15.5.0".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > graphiql@1.4.2" has incorrect peer dependency "react@^16.8.0".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > graphiql@1.4.2" has incorrect peer dependency "react-dom@^16.8.0".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > react-qr-reader@2.2.1" has incorrect peer dependency "react@~16".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > react-qr-reader@2.2.1" has incorrect peer dependency "react-dom@~16".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/hardhat > eslint-config-airbnb > eslint-config-airbnb-base@14.2.1" has unmet peer dependency "eslint-plugin-import@^2.22.1".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > graphiql > @graphiql/toolkit@0.2.2" has incorrect peer dependency "graphql@>= v14.5.0 <= 15.5.0".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > graphiql > codemirror-graphql@1.0.2" has incorrect peer dependency "graphql@>= v14.5.0 <= 15.5.0".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > graphiql > graphql-language-service@3.1.4" has incorrect peer dependency "graphql@>= v14.5.0 <= 15.5.0".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > web3modal > styled-components@5.3.0" has unmet peer dependency "react-is@>= 16.8.0".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > graphiql > codemirror-graphql > graphql-language-service-interface@2.8.4" has incorrect peer dependency "graphql@>= v14.5.0 <= 15.5.0".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > graphiql > codemirror-graphql > graphql-language-service-parser@1.9.2" has incorrect peer dependency "graphql@>= v14.5.0 <= 15.5.0".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > graphiql > graphql-language-service > graphql-language-service-types@1.8.2" has incorrect peer dependency "graphql@>= v14.5.0 <= 15.5.0".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > walletlink > eth-block-tracker > @babel/plugin-transform-runtime@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/hardhat > ethereum-waffle > @ethereum-waffle/compiler > typechain > ts-essentials@6.0.7" has unmet peer dependency "typescript@>=3.7.0".
warning "workspace-aggregator-2d691895-2743-472d-9cea-396bd7c83864 > @scaffold-eth/react-app > graphiql > codemirror-graphql > graphql-language-service-interface > graphql-language-service-utils@2.5.3" has incorrect peer dependency 

"graphql@>= v14.5.0 <= 15.5.0".
[4/4] Building fresh packages...
[9/21] ⢀ secp256k1
[15/21] ⢀ ursa-optional
[8/21] ⢀ keccak
[16/21] ⢀ keytar

**warning Error running install script for optional dependency: "/home/semiott/Apps/eth-apps/PolgarNet/scaffold-eth/node_modules/keytar: Command failed.
Exit code: 1**

Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /home/semiott/Apps/eth-apps/PolgarNet/scaffold-eth/node_modules/keytar
Output:
prebuild-install WARN install No prebuilt binaries found (target=14.0.0 runtime=node arch=x64 libc= platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.0.0 | linux | x64
gyp info find Python using Python version 3.9.5 found at \"/usr/bin/python3\"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/semiott/.nvm/versions/node/v14.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/semiott/Apps/eth-apps/PolgarNet/scaffold-eth/node_modules/keytar/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/semiott/.nvm/versions/node/v14.0.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/semiott/.cache/node-gyp/14.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/semiott/.cache/node-gyp/14.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/semiott/.nvm/versions/node/v14.0.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/semiott/.cache/node-gyp/14.0.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/semiott/Apps/eth-apps/PolgarNet/scaffold-eth/node_modules/keytar',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
**Package libsecret-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsecret-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsecret-1' found
gyp: Call to 'pkg-config --cflags libsecret-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/semiott/.nvm/versions/node/v14.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)**

**gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.11.0-31-generic
gyp ERR! command \"/home/semiott/.nvm/versions/node/v14.0.0/bin/node\" \"/home/semiott/.nvm/versions/node/v14.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /home/semiott/Apps/eth-apps/PolgarNet/scaffold-eth/node_modules/keytar**

success Saved lockfile.
Done in 253.64s.

**Comment by codenamejason** [comment]
Package libsecret-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing libsecret-1.pc' to the PKG_CONFIG_PATH environment variable No package 'libsecret-1' found gyp: Call to 'pkg-config --cflags libsecret-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp gyp ERR! configure error gyp ERR! stack Error: gyp` failed with exit code: 1
