### ISSUE TITLE
Yarn mint won't post to IPFS

### ISSUE THREAD

**Issue by DylanCkawalec** [scaffold-eth/scaffold-eth#380]
Where do We go to change the files to assets we want to try posting?
![Screen Shot 2021-09-04 at 11 25 43 PM](https://user-images.githubusercontent.com/43707795/132117652-f59b7eb7-46e2-4dc4-9001-9778c2eacb70.png)

**Comment by codenamejason** [comment]
looks like you need to call the transferOwnership(your frontend address) in the deploy or the constructor of the contract then you will be owner and able to mint

**Comment by codenamejason** [comment]
@DylanCkawalec were you able to resolve this so I can close this issue?
