### ISSUE TITLE
Testing Challenge Branch

### ISSUE THREAD

**Issue by captnseagraves** [scaffold-eth/scaffold-eth#393]
There is not good documentation or a good tutorial/branch around testing. It would be very valuable to have a good challenge around testing in order to tech the common experienced with smart contracts.

**Comment by StErMi** [comment]
I can do that, I've already fully covered challenge1 and challenge2 with full test coverage. Do we want to use those challenges or do we want to create a new one?

**Comment by StErMi** [comment]
These are the tests for challenge1: https://github.com/StErMi/scaffold-eth-challenge-1-decentralized-staking/blob/main/packages/hardhat/test/staker.js

These are the tests for challenge2: https://github.com/StErMi/scaffold-eth-challenge-2-token-vendor/blob/main/packages/hardhat/test/vendor.js

**Comment by captnseagraves** [comment]
Awesome! I think using a challenge that someone has already completed could be helpful. We just want to have them walk through the full process of setting up and writing tests. Right now there isn't a robust way to learn or great documentation. The most important things to cover would be instantiating and interacting with contracts, making sure they are correctly implementing the async/await calls for chain data etc. 

Is that helpful?

**Comment by StErMi** [comment]
@captnseagraves In my blog post I explain how to do that

Go to https://stermi.medium.com/how-to-write-your-first-decentralized-app-scaffold-eth-challenge-1-staking-dapp-b0b6a6f4d242 and find the section  `Exercise Part 3: Test Coverage`

Would that be a good fit to integrate it into the challenge documentation? I know that I'm asking a lot but maybe reviewing my blog post (that is more a longer explanation of the challenge and how to do that) would be good to understand if that it's a good blue-print to use when we want to create a challenge explanation

**Comment by StErMi** [comment]
@codenamejason would the issue be closed when I updated the second challenge with the updated readme (that cover test)?

**Comment by StErMi** [comment]
@codenamejason I think that at this point we should think to add a meaningful contract to the master and add tests directly to the master. The master branch should be something people take inspiration from and use as the kickstart of the next project for both react/solidity.

what do you think? I've released a new blog post that takes the example of a "world purpose", could that be an example to use? 

Here's the GitHub repo https://github.com/StErMi/solidity-template

**Comment by codenamejason** [comment]
@StErMi the mainnet-starter branch is the one to focus on for using for a production app.

**Comment by codenamejason** [comment]
move to challenges repo
