### ISSUE TITLE
Multiple Requests To Bottom Left Faucet Problem

### ISSUE THREAD

**Issue by jrbgit** [scaffold-eth/scaffold-eth#395]
After requesting funds from the faucet it is not possible to submit another request. The address that gets pasted into the text field can't be removed. Requesting a second time results in the following error message:

```
Transaction Error
provided ENS name resolves to null (argument="tx.to", value="", code=INVALID_ARGUMENT, version=providers/5.4.1)
```

The only way to request again is to refresh the page.

Additional details and steps to reproduce:
1. On master branch
2. Start up the environment as per the docs `yarn install` `yarn chain` `yarn start` `yarn deploy` etc.
3. Connect MetaMask wallet and copy the address
4. Paste address and request some ETH (this works)
5. Attempt to make a second request (this fails)
6. Unable to clear the address from the text field or paste the address again...

Mac OS X latest version
Node  v14.17.3
Yarn 1.22.11
npm 7.21.1

**Comment by codenamejason** [comment]
What I do is edit the Faucet.jsx to send more eth on the first tx. As to the issue you were having I will try to reproduce on my end and report back.

**Comment by jrbgit** [comment]
It looks like the issue stems from the fact that in Faucet.jsx on line 104 it does:

`setAddress("");`

However this doesn't actually clear the form box and as a result, like the error message says, the address field is blank.

**Comment by jrbgit** [comment]
Additionally, with metamask wallet connected, upon page load, the balance is being displayed as 0.00, but after requesting funds from the faucet - it updates to the correct balance that metamask shows. (The correct wallet address does show in the header the whole time) - commenting out line 104 does allow multiple requests from the faucet.

But it seems like after connecting metamask, the site is not getting the balance from the correct wallet - this may be a separate issue though.

**Comment by codenamejason** [comment]
Do we have the same issue when using the burner wallet instead of MM?

**Comment by jrbgit** [comment]
Yes. It looks like after the first transaction, the text in the box remains there, and trying to change it just keep firing off line 92 where it handles `onChange={e => {`

**Comment by harryranakl** [comment]
fix PR: https://github.com/scaffold-eth/scaffold-eth/pull/440

**Comment by codenamejason** [comment]
thanks @harryranakl
