### ISSUE TITLE
Update gas price for 1559

### ISSUE THREAD

**Issue by codenamejason** [scaffold-eth/scaffold-eth#401]

**Comment by codenamejason** [comment]
Update the gas price usage in some of the components for 1559.

**Comment by ShravanSunder** [comment]
don't we get the gas price from the eth-hooks which gets it from an api for mainnet?  in eth-hooks@v3 it uses estimateGasPrice from ethers for other networks.

**Comment by Peyton-Spencer** [comment]
Hey there, I want to help add support for EIP 1559! What steps need to be taken? Is eth-hooks ready for 1559? In the code I do not see `maxPriorityFeePerGas` and `maxFeePerGas`. Though these parameters are mentioned in `index.ts` in `challenge-0-simple-nft`

```ts
export interface Overrides {
    gasLimit?: BigNumberish | Promise<BigNumberish>;
    gasPrice?: BigNumberish | Promise<BigNumberish>;
    maxFeePerGas?: BigNumberish | Promise<BigNumberish>;
    maxPriorityFeePerGas?: BigNumberish | Promise<BigNumberish>;
    nonce?: BigNumberish | Promise<BigNumberish>;
    type?: number;
    accessList?: AccessListish;
    customData?: Record<string, any>;
};
```
