### ISSUE TITLE
Create a slide out for debug contracts

### ISSUE THREAD

**Issue by codenamejason** [scaffold-eth/scaffold-eth#405]
While navigating and testing your dapp you have to always go back to the debug page to test a contract directly. We are proposing adding a slide-out for the debug contracts with a selector of some sort to choose which contract you want to interact with.

**Comment by AntFrasier** [comment]
@codenamejason Hello,
I did something like that. I don't know if this is what expected :p 
Have a look if you'd like : https://scaffoldeth-cm-challenge3.surge.sh/
Code : https://github.com/AntFrasier/Forke-scaffold-eth-challenges/tree/challenge-3-dice-game
