### ISSUE TITLE
initiate problem: yanr install failed with Exit code: 128

### ISSUE THREAD

**Issue by jhfnetboy** [scaffold-eth/scaffold-eth#408]
**Describe the bug**
can't initiate with yarn install

**To Reproduce**
1. clone master
2. cd main directory
3. run "yarn" or "yarn install"
 yarn
yarn install v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning Pattern ["@apollo/client@latest"] is trying to unpack in the same destination "/Users/greed/Library/Caches/Yarn/v6/npm-@apollo-client-3.3.21-2862baa4e1ced8c5e89ebe6fc52877fc64a726aa-integrity/node_modules/@apollo/client" as pattern ["@apollo/client@^3.3.21"]. This could result in non-deterministic behavior, skipping.
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://github.com/AssemblyScript/assemblyscript
Directory: /Users/greed/Dev/game
Output:
error: RPC 失败。curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
error: 预期仍然需要 33 个字节的正文
fatal: 在引用列表之后应该有一个 flush 包
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

5.I have meet this question manytimes...
I replace "yarn" with "npm install", it is ok

**Expected behavior**
normal install

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 93?

**Comment by codenamejason** [comment]
<img width="1257" alt="Screen Shot 2021-09-14 at 4 19 14 PM" src="https://user-images.githubusercontent.com/9419140/133327995-e70e1b2f-2d51-4ed2-9d30-ba582a59f35c.png">


I am unable to reproduce and can successfully run yarn install.

**Comment by jhfnetboy** [comment]
It maybe the network problem, run command on the terminal with 
"export https_proxy=http://127.0.0.1:7890 \n
export http_proxy=http://127.0.0.1:7890\n
export all_proxy=socks5://127.0.0.1:7890\n"
The error seems never recur again.
 Thx for jason~!^_^
