### ISSUE TITLE
ENS names starting with 0x are not rendered as ENS names

### ISSUE THREAD

**Issue by QEDK** [scaffold-eth/scaffold-eth#420]
**Describe the bug**
ENS names that start with `0x` show up as addresses instead.

**To Reproduce**
1. Get an ENS starting with `0x` 😬 
2. Address will not display with ENS in most places

**Expected behavior**
It should show up as the ENS name.

**Screenshots**
<img width="1024" alt="Screenshot 2021-09-18 at 12 49 14 AM" src="https://user-images.githubusercontent.com/1272002/133842389-a18a6604-4d07-4eb3-a932-1806659cd3c8.png">

**Additional context**
First posted here: https://github.com/moonshotcollective/tip.party/issues/91#issuecomment-921925566
and fixed here: https://github.com/moonshotcollective/tip.party/pull/96

**Comment by harryranakl** [comment]
fix PR: https://github.com/scaffold-eth/scaffold-eth/pull/441
