### ISSUE TITLE
Remove the deploy.js script if we have adopted hardhat-deploy plugin

### ISSUE THREAD

**Issue by StErMi** [scaffold-eth/scaffold-eth#425]
As far as I get scaffold-eth have adopted the hardhat-deploy plugin approach to deploying contracts, the old `deploy.js` script file is not used anymore and we should remove it

**Comment by codenamejason** [comment]
@austintgriffith when do you think we can remove the old deploy method, I realize the older branches are still using it and they are in the process of all being brought up to master, so with that being said, we could get rid of the old deploy script. Thoughts??
