### ISSUE TITLE
Prune most of the network in hardhat.config.js

### ISSUE THREAD

**Issue by StErMi** [scaffold-eth/scaffold-eth#426]
Inside the `hardhat.config.js` we have tons of networks and IMHO most of them are just "useless" for the general-purpose configuration.

I think that we should just have 

- local
- one testnet (rinkeby?)
- maybe main net

And point to the scaffold-eth documentation site or hardhat docs if you need to configure more

**Comment by codenamejason** [comment]
What about having them commented below for the user to 'pick' them out if they want to use them. I use kovan and only rinkeby for nft testing so I think picking one testnet will not work. @azf20 what do you think? ^^^^

**Comment by codenamejason** [comment]
This is something we may do on the mainnet-starter branch and the moonshot-starter branch.
