### ISSUE TITLE
Create a hardhat-tasks repository

### ISSUE THREAD

**Issue by StErMi** [scaffold-eth/scaffold-eth#427]
Hi there, inside the current `hardhat.config.js` we have tons of tasks.

I would like to know

- which ones are still used? I would like to discard those tasks that are not used anymore
- can I create a separate repo where I can create a hardhat plugin that contains all those tasks?

That repo would be written in typescript and we would just import the project as a normal hardhat plugin dependency

**Comment by ShravanSunder** [comment]
as side information, the typescript repo has a typescript version of harhat.config.ts with many tasks.  https://github.com/scaffold-eth/scaffold-eth-typescript/blob/main/packages/hardhat-ts/hardhat.config.ts

**Comment by codenamejason** [comment]
created, now we just have to buidl it 🏰
