### ISSUE TITLE
Token List/Custom Token Component

### ISSUE THREAD

**Issue by codenamejason** [scaffold-eth/scaffold-eth#443]

**Comment by codenamejason** [comment]
Create a TokenList component that devs can just use. You can use the uniswap list to start.

**Comment by azf20** [comment]
I think there is a token list hook already which could feed this? 

https://github.com/scaffold-eth/scaffold-eth/blob/master/packages/react-app/src/hooks/TokenList.js

**Comment by codenamejason** [comment]
yes, thanks @azf20
