### ISSUE TITLE
Update scaffold-eth `master` to use new eth-components

### ISSUE THREAD

**Issue by ShravanSunder** [scaffold-eth/scaffold-eth#449]
Create eth-components: 
See project notes for details:  https://github.com/orgs/scaffold-eth/projects/2#card-69618246

**Comment by ghostffcode** [comment]
Please let's make sure these have been properly tested before implementing it

**Comment by codenamejason** [comment]
@ghostffcode going to look at the component v1 repo and see if it has tests

**Comment by ShravanSunder** [comment]
Eth-components has no tests in any version. Only eth-hooks does @codenamejason
