### ISSUE TITLE
when the rpc runs out of requests we need to handle gracefully

### ISSUE THREAD

**Issue by codenamejason** [scaffold-eth/scaffold-eth#451]
**Describe the bug**
when the rpc runs out of requests we need to handle gracefully
The app blows up when no more requests.

**Comment by codenamejason** [comment]
@brendanboyle87 yeah, we just use the infura id that comes with the master branch and it should fail fairly quickly.

**Comment by ghostffcode** [comment]
@codenamejason is this still an open issue?
