### ISSUE TITLE
yarn graph-ship-local fails: "The current version of graph-cli can't be used with mappings on apiVersion less than '0.0.5'"

### ISSUE THREAD

**Issue by jrbgit** [scaffold-eth/scaffold-eth#456]
After a fresh clone from master branch and the typical `yarn install` `yarn chain` `yarn deploy`  `yarn start` etc -   An attempt to launch subgraph following the commands on the page subgraph page fails on the last step -  `yarn graph-ship-local`

I have performed these steps in the past and normally it works fine. (Expected behaviour)

Desktop:
 - Mac OS X 11.6
 - Chrome / Brave
 - Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (x86_64)

Output from `yarn graph-ship-local`

`The current version of graph-cli can't be used with mappings on apiVersion less than '0.0.5'`

https://github.com/scaffold-eth/scaffold-eth/blob/master/packages/subgraph/src/subgraph.template.yaml is using 0.0.4

**Comment by jrbgit** [comment]
It seems like this issue may have happened when these packages were upgraded in this commit:

https://github.com/scaffold-eth/scaffold-eth/commit/8a38a96d1479f0107825a4b2a7d0e306f351d236

Changing:

`"@graphprotocol/graph-cli": "^0.22.0",`
 `"@graphprotocol/graph-ts": "^0.22.0"`
 
 Back to:
 
`"@graphprotocol/graph-cli": "0.18.0",`
 `"@graphprotocol/graph-ts": "0.18.0"`

Results in the expected behaviour.


It looks like https://github.com/scaffold-eth/scaffold-eth/blob/master/packages/services/graph-node/docker-compose.yml

`image: graphprotocol/graph-node:2c23cce` needs to be updated to a newer tag...

I quickly dropped in `:latest` just for the fun of it and it _looks_ like it will solve the problem.  I need to do some additional testing to see what the correct tag should be to work with the upgraded packages.... (It's 0:30 here so that's all I can do for tonight) :)

**Comment by codenamejason** [comment]
@jrbgit thanks for tackling this, do you think you could submit a pr with a fix using the updated packages?

**Comment by codenamejason** [comment]
@azf20 what do you think a solution to this would be?

**Comment by azf20** [comment]
@jrbgit was basically there (thanks!)
- update graph-node to latest
- update subgraph apiVersion to latest
- update null check per the migration guide (https://thegraph.com/docs/developer/assemblyscript-migration-guide)
This PR is maybe right but I haven't actually run it e2e https://github.com/scaffold-eth/scaffold-eth/pull/457
