### ISSUE TITLE
Use MetaMask's network switching API when available

### ISSUE THREAD

**Issue by danfinlay** [scaffold-eth/scaffold-eth#482]
Currently if a user is on the wrong network, a helpful dialog is shown:

<img width="490" alt="Screen Shot 2021-10-09 at 8 31 29 PM" src="https://user-images.githubusercontent.com/542863/136680670-f83efff2-9c06-4ac0-ac67-de81e887d386.png">

MetaMask now supports suggesting a network switch via API, which can make this slightly easier (initiated from a button click within the dapp UI). [wallet_switchEthereumChain docs](https://docs.metamask.io/guide/rpc-api.html#wallet-switchethereumchain).

I'd call this current MetaMask best practice, so it'd be great to have it in scaffold-eth for new projects to inherit!

**Comment by brendanboyle87** [comment]
I think this was implemented? https://github.com/scaffold-eth/scaffold-eth/blob/master/packages/react-app/src/App.jsx#L343 This could be nice - https://consensys.net/blog/metamask/connect-users-to-layer-2-networks-with-the-metamask-custom-networks-api/?utm_content=156337458&utm_medium=social&utm_source=twitter&hss_channel=tw-3278906401 if a user doesnt have it configured
