### ISSUE TITLE
Request to infura fails when running "yarn mint" on branch "simple-nft-example"

### ISSUE THREAD

**Issue by Danielrachi** [scaffold-eth/scaffold-eth#496]
**Describe the bug**
I'm following the README on the simple-nft-example branch, when It's time to execute "yarn mint" for the first time, the command fails.

**To Reproduce**
(Just following the README on simple-nft-example)
1.  Execute the following on a terminal window:
    git clone https://github.com/austintgriffith/scaffold-eth.git simple-nft-example
    cd simple-nft-example
    git checkout simple-nft-example
    yarn install
    yarn start
2. On a second terminal window:
    cd simple-nft-example
    yarn chain
3. Third terminal window:
    cd simple-nft-example
    yarn deploy
4.  Edit the mint script mint.js in packages/hardhat/scripts and update the toAddress to your frontend address. To do that:
    run: code .
    Edit the mint address in the  mint.js file as the readme indicates.
5. On the third terminal window (the one on step 3) run:
    yarn mint 

**Expected behavior**
As the README indicates, I was expecting to mint the NFT to the address shown in my frontend
![image](https://user-images.githubusercontent.com/67139425/137573432-82fd8c1d-a434-4ca7-855c-95ec323424b0.png)
![image](https://user-images.githubusercontent.com/67139425/137573439-02d028bf-99dc-4fcd-a9f8-74e2770e3464.png)

**Screenshots**
This is the error I get:
![image](https://user-images.githubusercontent.com/67139425/137573465-13413af6-8f83-439a-b6e4-c2575c4a72c0.png)

And of course, the NFT doesn't show in my frontend:
![image](https://user-images.githubusercontent.com/67139425/137573763-0ab651ca-d1ca-4506-8c7a-e81b93a7d828.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, running Ubuntu 20.04.3 LTS on WSL2
 - Browser: Brave
 - Version 1.30.89 Chromium: 94.0.4606.81 (Official Build) (64-bit)

**Comment by wufengtao1** [comment]
Me too , and I have used a proxy.
