### ISSUE TITLE
Better docker explanation please

### ISSUE THREAD

**Issue by wojciech-turek** [scaffold-eth/scaffold-eth#527]
Hey Team,

I am quite new to docker and saw that you technically allow using it here: https://github.com/scaffold-eth/scaffold-eth/tree/master/docker

When I run the commands it says `Error: No such container: SCAFFOLD_ETH` .

Can someone please share with me what steps I must take before for it to work?

Thanks,
W

**Comment by piraces** [comment]
Hello,

I can work on this if you are ok with it 😃

**Comment by piraces** [comment]
Hey @wojciech-turek ,

If you are executing the `setup.sh` script for now you just can ignore the error thrown in first instance and the script will create the docker container.

For the other commands just avoid executing `docker rm -f SCAFFOLD_ETH` before `docker run ...` if you don't have any container previously created.

Hope this helps!
