### ISSUE TITLE
Scaffold-Eth is way too bloated

### ISSUE THREAD

**Issue by daweth** [scaffold-eth/scaffold-eth#538]
**Describe the bug**
Scaffold-eth is way too big and has too many features for it to be a good starting point for beginners. I think it's even more complex than many production frontends, but not only that, is more clumsy and has bad practices compared to production frontends. There are purposeless abstractions, way too many features, etc.

**Comment by azf20** [comment]
hey @daweth! we're always looking to make scaffold-eth work better as a builder's toolkit and general onboarding tool. It is definitely pretty complex right now. Are there specific practices, abstractions or features that you would prioritise changing?
