### ISSUE TITLE
zkSync Starter Kit

### ISSUE THREAD

**Issue by codenamejason** [scaffold-eth/scaffold-eth#542]
The goal here would be to create a starter kit in 🏗 scaffold-eth that demonstrates the capabilities of zkSync 2.0. We would like to time the release with the new zkSync coming out. A good starter kit is easily forkable with a good readme. We usually show off a starter kit by building something cool with it too.

**Comment by AbhinavMir** [comment]
Hi, is there a demo for this for ZKSync 2.0?
