### ISSUE TITLE
Cannot pass struct or tuple as a parameter

### ISSUE THREAD

**Issue by djibomar** [scaffold-eth/scaffold-eth#555]
**Describe the bug**
Using the UI, I'm unable to call a function that accepts struct or tuple as a parameter.

**To Reproduce**
1. Create a struct in YourContract
2. Create a variable for the struct
3. Create a function that set the value of the struct
4. After compiling and deploying, call your function by passing a tuple [foo, bar]

**Expected behavior**
The struct value is set

**Screenshots**
![Screen Shot 2021-11-11 at 9 58 43 PM](https://user-images.githubusercontent.com/6314730/141401719-48929db9-1e42-437a-ab6d-10b52030ec4f.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome

**Additional context**

**Comment by codenamejason** [comment]
can you show your setName code? I am not sure this is a Scaffole-eth 🏗  problem?
