### ISSUE TITLE
Setting the value of '-walletlink:https://www.walletlink.org:version' exceeded the quota.

### ISSUE THREAD

**Issue by Garinmckayl** [scaffold-eth/scaffold-eth#564]
I am getting this issue on a clean installation `QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of '-walletlink:https://www.walletlink.org:version' exceeded the quota.`

**Comment by codenamejason** [comment]
At what point in the setup are you @Garinmckayl? Can you share some more context please and some screen shots?
