### ISSUE TITLE
Link for scaffoldeth.io in the "About" section of this repository does not work

### ISSUE THREAD

**Issue by piraces** [scaffold-eth/scaffold-eth#587]
Hello,

Not sure if this is the right place to post this, but I have detected that in the "About" section in this repository, the link to scaffoldeth.io is https://scaffoldeth.io/ which does not redirect to the GitHub repository and fails to load.

Instead, if you open http://scaffoldeth.io/ it redirects you correctly.

I think it could lead some users to some confusion...

Some possible fixes would be to redirect the domain when accesing with https or to change the link in the "About" section to "http://scaffoldeth.io/".

**Comment by codenamejason** [comment]
@austintgriffith is this something you handle ser?
