### ISSUE TITLE
Ethereum App Failed to compile 

### ISSUE THREAD

**Issue by hsy505** [scaffold-eth/scaffold-eth#617]
Chrome shows

./src/components/AddressInput.jsx
Attempted import error: 'useLookupAddress' is not exported from 'eth-hooks'.

macOS Monterey 12.0.1
Chrome 96.0.4664.110

**Comment by Khaleelsm** [comment]
Debug it and run it again

**Comment by codenamejason** [comment]
has this issue been resolved?

**Comment by hsy505** [comment]
> has this issue been resolved?

just closed it
