### ISSUE TITLE
Deploy Subgraph Error: Ethereum network not supported by registrar: no network localhost found on chain ethereum

### ISSUE THREAD

**Issue by wip-abramson** [scaffold-eth/scaffold-eth#640]
**Describe the bug**
Running into an error when attempting to deploy a subgraph for the basic YourContract example. Subgraph builds, and is uploaded to ipfs fine. But run into the following error when deploying to local graph node.

✖ Failed to deploy to Graph node http://localhost:8020/: Ethereum network not supported by registrar: no network localhost found on chain ethereum

**To Reproduce**
1. Follow these steps - https://docs.scaffoldeth.io/scaffold-eth/getting-started/quick-start
2. Uncomment SetPurpose event code from YourContract.sol
3. Deploy subgraph following these commands- https://docs.scaffoldeth.io/scaffold-eth/toolkit/infrastructure/the-graph

**Expected behavior**

Subgraph to deploy to local graph network.

**Comment by samlaf** [comment]
I'm running into the exact same error.
Would be nice to know how to fix this.
I tried following this [stackoverflow answer](https://ethereum.stackexchange.com/a/102378/85362) by starting the hardhat local network with `yarn chain --hostname 0.0.0.0`, but it didn't solve the problem.

I also noticed when I run `yarn run-graph-node` I get:
```
graph-node_1  | Jan 25 23:24:34.128 WARN Trying again after eth_getBlockByNumber(0, false) RPC call failed (attempt #13) with result 
Err(Transport error: Error(Connect, Custom { kind: Uncategorized, error: "failed to lookup address information: Name or service not known" })), provider: localhost-rpc-0
```
which seems to indicate that the graph docker can't connect to the local hardhat chain?

**Comment by codenamejason** [comment]
@azf20 would you have any insight on this?

**Comment by Ataxia123** [comment]
ran into the same probllem and I just fixed it!

Had to do two things to make it work:
1) change hostname to 0.0.0.0 instead of default
  yarn chain  --hostname 0.0.0.0 


 2) add     host-gateway to the docker-compose file as reported in this StackOverflow question https://stackoverflow.com/questions/48546124/what-is-linux-equivalent-of-host-docker-internal/67158212#67158212
"
...
extra_hosts:
      - "host.docker.internal:host-gateway"
...
"
