### ISSUE TITLE
Great Starter Feature - add <Balance/> to the <Contract/> object

### ISSUE THREAD

**Issue by austintgriffith** [scaffold-eth/scaffold-eth#644]
Right now the <Contract/> object only shows the <Address/> of the contract and not the <Balance/> too.

![image](https://user-images.githubusercontent.com/2653167/149838288-b3f43af8-72fd-4198-97f4-c184e78edce2.png)

Please add the <Balance/> of the contract too so it's easy to see when the <Contract/> receives value.

Here it is in the code: 
https://github.com/scaffold-eth/scaffold-eth/blob/master/packages/react-app/src/components/Contract/index.jsx#L124

**Comment by adnfx2** [comment]
Seems good to me :) - I was wondering what the 'price' prop does, it took me a while to find out that it's only meant to do the conversion into USD. Maybe we should call it ethPrice or something else :sweat_smile:
