### ISSUE TITLE
After Build Got A 404 in "/debugcontracts" Subdirectory

### ISSUE THREAD

**Issue by 0x471** [scaffold-eth/scaffold-eth#664]
Hi everyone, I build my project using ```yarn build``` command. After uploading the "build" folder to surge, I tried to open _.....(.)surge.sh/debugcontracts_ but got a 404 error. Also same situation happens in netlify. Thanks in advance, have a nice day.

nnntokenmint.surge.sh | deployed website
https://github.com/selimerunkut/nnn_minting_ui | codes

**Comment by codenamejason** [comment]
When you uploaded to surge, do you mean you ran `yarn surge` @0x471

**Comment by 0x471** [comment]
Thanks for the response, handled it
