### ISSUE TITLE
Scaffold-eth NextJS documentation ERROR

### ISSUE THREAD

**Issue by thedarkknight197** [scaffold-eth/scaffold-eth#668]
Hi i have an issue with your documentation to install nextjs version of scaffold-eth.

The right steps are:

```
git clone https://github.com/austintgriffith/scaffold-eth.git scaffold-eth
cd scaffold-eth
```
Moving to remote nextjs branch:
```
git fetch origin
git checkout scaffold-nextjs
```

Now are in the right branch wit the nextjs files

**Comment by codenamejason** [comment]
I updated the checkout line of code for you. What was the issue with the documentation so we can make it better 🤔

**Comment by thedarkknight197** [comment]
I see the old version here: https://github.com/scaffold-eth/scaffold-eth/tree/scaffold-nextjs
The problem was the checkout command, if you do with cloning without fetch remote branche the command will create a new branch, but not moving on remote branche to use nextjs template.

I write the issue to help update the readme file on tree nextjs, to help people to type right command   😄

**Comment by codenamejason** [comment]
the next-js branch that is going to be maintained lives in the examples repo.

**Comment by thedarkknight197** [comment]
Could you share the right repo please?

**Comment by codenamejason** [comment]
Scaffold-Eth/scaffold-eth-examples

**Comment by thedarkknight197** [comment]
<img width="1338" alt="Schermata 2022-02-07 alle 13 50 34" src="https://user-images.githubusercontent.com/37689698/152791346-0df64974-6da2-417a-b426-07a2dcefc3cf.png">
I don't see that :/

**Comment by codenamejason** [comment]
Https://github.com/scaffold-eth/scaffold-eth-challenges
