### ISSUE TITLE
Deploying openzeppelin upgradeable contracts - functions not showing in the Debug UI

### ISSUE THREAD

**Issue by vladx777** [scaffold-eth/scaffold-eth#676]
Openzeppelin upgradeable contracts require using upgrades plugin when deploying. 

It doesn't seem to work with Scaffold eth though as a deployed contract is not showing up in the Debug UI tab.

Easy to repro - generate an ERC1155 upgradeable contract in OZ's wizard and replace YourContract.sol with the code. Then in your deploy js script run:
``` 
const { ethers, upgrades } = require("hardhat");
const YourContract = await ethers.getContractFactory("YourContract");
  const instance = await upgrades.deployProxy(YourContract);
```
You won't see the contract functions in the UI. How can this be fixed?

**Comment by codenamejason** [comment]
This will have to be investigated further. Are you interested in hunting down a solution and submitting a PR? @vladx777

**Comment by supernovahs** [comment]
I can try it and make a PR if you say so

**Comment by Kaylin6688** [comment]
SUN DeFi is the safest financial product, profitable every day, every week, high deposit interest in ETH and TROX, USDT
 daily interest:
 deposit 5000usdt = 630 USDT
 deposit 30,000usdt=750 USDT
 deposit 60,000usdt= 1920 USDT
 deposit 80,000usdt= 2880 USDT
 deposit 100,000usdt = 4000USDT
 inbox for detailed advice: https://www.funawealth.com?share_address=0x0E2E7bb6D1A83eDAB9C84411C018a050E7BE406C
