### ISSUE TITLE
Error HH604: Error running JSON-RPC server: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by john-difool** [scaffold-eth/scaffold-eth#691]
yarn run v1.22.17
$ yarn workspace @scaffold-eth/hardhat chain
$ hardhat node --network hardhat --no-deploy
✔ Help us improve Hardhat with anonymous crash reports & basic usage data? (Y/n) · true

Error HH604: Error running JSON-RPC server: error:0308010C:digital envelope routines::unsupported

For more info go to https://hardhat.org/HH604 or run Hardhat with --show-stack-traces
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /Users/johnny/.nvm/versions/node/v17.5.0/bin/node
Arguments: /Users/johnny/.nvm/versions/node/v17.5.0/lib/node_modules/yarn/lib/cli.js chain
Directory: /Users/johnny/Projects/scaffold-eth/scaffold-eth/packages/hardhat
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by rvanv** [comment]
use node 16 and lower
