### ISSUE TITLE
Error HH307: Missing Positional Argument address

### ISSUE THREAD

**Issue by supernovahs** [scaffold-eth/scaffold-eth#701]
When verifying a contract in the master repo, hardhat is throwing this error
![Screenshot from 2022-03-05 18-12-39](https://user-images.githubusercontent.com/91280922/156883589-ba6bd476-20cb-4f14-9bc5-8b5b1441a5f7.png)

**Comment by adamskrodzki** [comment]
Too little information to be certain, but my guess is you need to say what do you want to verify and also add all constructor values and network if applicable

so minimal command would be like 

`yarn verify >>contractDeploymentAddress<<` 

possibly followed by constructor arguments

**Comment by supernovahs** [comment]
It should work by entering this yarn verify --network "network name "
But is throwing error.

**Comment by codenamejason** [comment]
@supernovahs have you resolved this?

**Comment by supernovahs** [comment]
Yeah, It solved by doing this command yarn verify -- contract Address -- "Network Name"

**Comment by robksawyer** [comment]
@supernovahs can you confirm the syntax above. There seem to be some strange spaces.

```yarn verify -- contract Address -- "Network Name"```

**Comment by Quanhua-Guan** [comment]
<img width="1400" alt="2022-08-02 14 04 07" src="https://user-images.githubusercontent.com/1726550/182303602-9f0a7f07-ffe3-4cdc-9b07-88f7db9f7419.png">

Here is the solution for the problem i met (Hope it helps):

in `packages/hardhat/package.json` at the bottom, change the script command of `"verify": "hardhat verify"` to `"verify": "hardhat etherscan-verify --api-key PSW8C433Q667DVEX5BCRMGNAH9FSGFZ7Q8"`

re-run `yarn verify --network rinkeky` (you need to change the network to the chain where your contract deployed)

**Comment by RostyslavDzhohola** [comment]
I have a similar issue, but for `hardhat balance`
![image](https://user-images.githubusercontent.com/30268115/194683019-0cc463d8-fa5b-4aa7-b025-5a817a38ed27.png)

**Comment by Zodomo** [comment]
@RostyslavDzhohola create a new issue for this as this issue is closed and that's for a different command. Be sure to include your CLI output and errors from running it.
