### ISSUE TITLE
IPFS script is using outdated IPFS version when on 55.0.0

### ISSUE THREAD

**Issue by jonathanng1122** [scaffold-eth/scaffold-eth#713]
# Overview 

When try to run `yarn run ipfs` on the master branch, it gives the following error:

<img width="751" alt="image" src="https://user-images.githubusercontent.com/87622099/159122376-452ee692-7e34-4a6d-9af6-05b564c9077f.png">

# How to recreate:
 1. Using the master branch and after doing all of the required building, run `yarn run ipfs` and you should get the above error.

# Problem
The issue at its core is that the `ipfs-http-client` package version was increased to a version which changed it's API.

I have attached the changed code to fix the issue:

I would love to be added as a contributer and do the changes myself if possible.

# The Fix

We have 2 options:
 - downgrade the package to compatible version with the script
 - the script can be updated to match the new API.

## Updating the script
```
const {create, globSource} = require("ipfs-http-client");
const chalk = require("chalk");
const { clearLine } = require("readline");

const infura = { host: "ipfs.infura.io", port: "5001", protocol: "https" };
// run your own ipfs daemon: https://docs.ipfs.io/how-to/command-line-quick-start/#install-ipfs
// const localhost = { host: "localhost", port: "5001", protocol: "http" };

const ipfs =  create(infura);

const ipfsGateway = "https://ipfs.io/ipfs/";
const ipnsGateway = "https://ipfs.io/ipns/";

const addOptions = {
  pin: true,
  wrapWithDirectory: true
};

const pushDirectoryToIPFS = async path => {
  try {
    const file = ipfs.addAll(globSource(path, '**/*'), addOptions)
    let lastRes;
    for await (const f of file) {
      lastRes = f
    }
    return lastRes
  } catch (e) {
    console.log(e)
    return {};
  }
};

const publishHashToIPNS = async ipfsHash => {
  try {
    const response = await ipfs.name.publish(`/ipfs/${ipfsHash}`);
    console.log(response)
    return response;
  } catch (e) {
    return {};
  }
};
```

I would do a pull request but I don't have the permissions to do so.

(Hopefully, I'm not severely missing something...)

**Comment by PowVT** [comment]
I am running into the same issue with the ipfs-http-client package. I believe it is the new version as well. Looking for a compatible version.

**Comment by jonathanng1122** [comment]
@PowVT  I believe if you downgrade to ipfs-http-client 33.0.0, the script should run.

**Comment by codenamejason** [comment]
@jonathanng1122 would be interested in creating a PR for this?

**Comment by jonathanng1122** [comment]
@codenamejason  Thank you! I didn't realize I can do that. I have submitted a pr #714 .
