### ISSUE TITLE
Module parse failed: Unexpected token (107:38) for the graphql-language-service

### ISSUE THREAD

**Issue by limcheekin** [scaffold-eth/scaffold-eth#716]
Hi there,

Newbie here. This is the first time I run the react-app of the scaffold-eth using the `yarn start` command.

I'm facing the following error in Ubuntu Linux: 
```
scaffold-eth/node_modules/graphql-language-service/esm/parser/onlineParser.js 107:38
Module parse failed: Unexpected token (107:38)
File was processed with these loaders:
 * ../../node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| 
|     if (state.needsSeperator) {
>       expected = expected && expected?.separator;
|     }
|
```
May I know anyone facing the same error and any solution?

Please advise. Thank you.

**Comment by limcheekin** [comment]
Workaround to keep the ball rolling.

Replace the codes in node_modules/graphql-language-service with [graphql-language-service.zip](https://siasky.net/3AEhCsJce4aNhotjIap6L-2v8m3-s9I6OttHmD66thpZgw).

**Comment by codenamejason** [comment]
Not a lot of people use the subgraph feature of Scaffold-Eth. I am glad you found a quick workaround. Is this something you could submit a PR for?

**Comment by limcheekin** [comment]
The workaround is in the codes of the graphql-language-service package, PR is not applicable.

**Comment by limcheekin** [comment]
It is working fine with the latest code. Let me close the issue.
