### ISSUE TITLE
Stuck in deploying "YourContract"

### ISSUE THREAD

**Issue by limcheekin** [scaffold-eth/scaffold-eth#720]
Hi there,

Thanks for creating such a great tool for Ethereum solidity/dapps learner. 

I think it is quite demotivating for any new user of the tool to hit few speed bumps just to "Quick Start".

My environment:
Ubuntu 20.04.4 LTS
Node v16.14.0
Npm 8.3.1

I run `yarn deploy` after `yarn chain`, the `deploying "YourContract"...` seems take forever.

Then I went ahead to make a small amendment to `YourContract.sol`, then run `yarn deploy` again, it prompt me the following message:
```
It used a gas pricing config of (gasPrice: 875000000 wei) ,
              current gas price is 1768762328 wei
              
              
? Choose what to do with the pending transaction: … 
▸ increase gas
  continue waiting
  skip (forget tx)
```

I choose the `iincrease gas` option, the command is exit with the following error:
```
nonce has already been used
```

Please advice. Thank you.

**Comment by codenamejason** [comment]
Try skip and it should use a new nonce @limcheekin

**Comment by limcheekin** [comment]
I tried the skip option, it is still stuck and the following is additional logs for your reference:
```
Downloading compiler 0.8.4
Compiling 2 files with 0.8.4
Compilation finished successfully
transaction 0xf3fd199d147b93f179619a35956ff5efeb7c1662eddf25e254263583f5ec8d8c still pending... It used a gas pricing config of (gasPrice: 875000000 wei) ,
              current gas price is 1768762415 wei
              
              
✔ Choose what to do with the pending transaction: · skip (forget tx)
deploying "YourContract" (tx: 0x6c75e6d69f50219e9926a91275a6d9074ca72ed082472a6997faab201bf4421c)...
```

I restarted the local chain while deploying, it is still stuck. 

Then I Ctrl+C to terminate it and  I re-deploy using `yarn deploy`, it is still stuck.

Hope this clarify. Please advise. Thank you.

**Comment by limcheekin** [comment]
Thanks for the quick response. 

I tried the `yarn deploy --reset`, unluckily it doesn't works. :(

The following is console logs of the `yarn chain`:
```
eth_sendTransaction
  Contract deployment: YourContract
  Contract address:    0x5fbdb2315678afecb367f032d93f642f64180aa3
  Transaction:         0xa67de92c96c0632591c0162b594553620432ef20ea41c64a26ff996522989614
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  Value:               0 ETH
  Gas used:            393058 of 393058
  Block #1:            0x0ab4ebdcd0058cd279b20269700624427b61714749a3b0d850172ed466b5b685
```

The following is console logs of the `yarn deploy --reset`:
```
yarn run v1.22.15
$ yarn workspace @scaffold-eth/hardhat deploy --reset
$ hardhat deploy --export-all ../react-app/src/contracts/hardhat_contracts.json --reset
Nothing to compile
deploying "YourContract" (tx: 0xa67de92c96c0632591c0162b594553620432ef20ea41c64a26ff996522989614)...
```
Hope this clarify. Thanks.

**Comment by pankaj512** [comment]
Could you please DM me on Telegram @pkmahan512 and let resolve it over there

**Comment by limcheekin** [comment]
@pankaj512 thanks for your suggestion on clone the fresh repo and do `yarn install`, `yarn start`, `yarn chain` and then `yarn deploy`. It works now even I not sure what had been changed in the past few days or the issue just happened to me. Thank you very much for your support. :)

**Comment by fourcolors** [comment]
I just cloned and am stuck on this. I'm having the exact same problem as @limcheekin

**Comment by Lisanaaa** [comment]
1. I got lots of yarn install issue when I cloned this repo at the first time, I figured it out it's because I am using Yarn version 3.x, and it is not compatible with the yarn.lock file in this repo. 
2. After switched to Yarn version 1.x, I got the same issue with @limcheekin.
3. Then I removed the whole repo and reclone it, issue all resolved, I guess the issue in `step 2` is because the Yarn version 3.x has left some bad config which caused this happen.

I will raise a Pull Request to fix the `README.md` in case others get into this trouble again.

**Comment by synbiokz** [comment]
I received an erno 2 no script named 'chain' error when I attempted the yarn chain command in terminal.
Repository downloaded Nov 24 2022
Node 18.12.1
yarn 3.2.2

I rolled back to yarn 1.22.19 and removed and recloned the scaffold-eth repository. "yarn chain" executed successfully

**Comment by synbiokz** [comment]
Similar issue with nodejs 18XX. You've already covered this by upfront telling us the versions of yarn and nodejs to use in the README. Switching to a stable release of nodejs 16xx fixed the issue of an error when running "yarn start". Just an FYI and thank you for being precise!
