### ISSUE TITLE
00_deploy_contract etherscan verify part wrong argument for verify

### ISSUE THREAD

**Issue by 0xCornelius** [scaffold-eth/scaffold-eth#728]
Hi! Seems like I cannot send a PR request so putting this issue.

For https://github.com/scaffold-eth/scaffold-eth/blob/master/packages/hardhat/deploy/00_deploy_your_contract.js on verify:verify it has the parameter contractArguments for arguments but it should be constructorArguments as per this: https://hardhat.org/plugins/nomiclabs-hardhat-etherscan.html

**Comment by codenamejason** [comment]
thank you for the heads up @0xCornelius
