### ISSUE TITLE
How to capture an error (revert) with Transactor

### ISSUE THREAD

**Issue by DoDzilla-ai** [scaffold-eth/scaffold-eth#739]
I understand some work has been done related to this issue ([here](https://github.com/scaffold-eth/scaffold-eth/issues/224)) but I don't understand how to capture an error if I am using the [Transactor](https://docs.scaffoldeth.io/scaffold-eth/toolkit/scaffold-eth-toolbox/eth-services). Since there is no documentation regarding this I couldn't handle the errors. I am getting `Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'wait')` because the `tx` is undefined if an error occurs. How can I capture the error? I think there needs to be information about capturing errors in documentation as well. Below is my code:

```
// scaffold-eth's Transactor helper gives us a nice UI popup when a transaction is sent. Transactor is a function.
const transactor = Transactor(provider, gasPrice);
const tx = await transactor(contract.redeem(ownerAddress, 0, voucher, {value: amount}));
//Here the tx is undefined since the transaction reverted (failed)
// Wait for the transaction to be confirmed, then get the token ID out of the emitted Transfer event.
const receipt = await tx.wait();
```

**Comment by codenamejason** [comment]
Example:

await tx(
      writeContracts &&
        writeContracts.TalentDaoNftToken &&
        writeContracts.TalentDaoNftToken.mintNFTForArticle(
          address,
          "https://myipfsuri.com/",
          ethers.utils.parseEther("1"),
        ),
      async update => {
        console.log("📡 Transaction Update:", update);
        if (update.status === 1) {
          notification.open({
            message: "Article NFT Purchased",
            description: "Your NFT has been transferred to your wallet 😍",
            icon: "🚀",
          });
        }
      },
    );

**Comment by tony123S** [comment]
I'm getting this issue too..how to fix?
