### ISSUE TITLE
Camera error: 

### ISSUE THREAD

**Issue by EngrGord** [scaffold-eth/scaffold-eth#752]
On mobile home screen, if QR code camera permission is denied once, it remains denied even on reload.

**Comment by codenamejason** [comment]
This has to do with permissions on your PC.

**Comment by EngrGord** [comment]
Yes shouldn't I be able to make a different choice when I want to use the application at a different time?.
This happens on mobile and PC.
I know how to change the permissions, but a nontechnical user might not be able to do this and I believe it's possible to make this user experience better. I hope to make a pull request when i get chanced to look into the logic.
