### ISSUE TITLE
Quick start is broken

### ISSUE THREAD

**Issue by chris13524** [scaffold-eth/scaffold-eth#800]
On the latest commit and starting with 9880f1402567d6bd6fcea7cb0f867bceaff71092, following the quick start yields this broken UI:

![image](https://user-images.githubusercontent.com/1979423/172753025-8730b4fa-f353-4f26-8afe-4c473cd1dc79.png)

And when entering a new purpose, I get this:

![image](https://user-images.githubusercontent.com/1979423/172753197-a6d617f5-3b9f-4805-a5a4-22db6b73437d.png)

However, on commit c75a21879a016817281fdcea461678b43d5da188 the UI works as expected:

![image](https://user-images.githubusercontent.com/1979423/172752866-a706b7d3-a405-4538-bd6c-bdba0239ea9b.png)

**Comment by chris13524** [comment]
[This change](https://github.com/scaffold-eth/scaffold-eth/pull/793/files#diff-029d750c1a6414d0d027607385e39afcd3024f3723185261a95f2baa791b344eR22) seems to be culprit. Reverting this on master fixes the issue for me

**Comment by chris13524** [comment]
I am using the devcontainer, which causes `REACT_APP_CODESPACES` to be true, thus causing this issue: https://github.com/scaffold-eth/scaffold-eth/blob/master/.devcontainer.json#L16

**Comment by codenamejason** [comment]
@chris13524 I am not able to reproduce this with latest master. What type of os are you using and how are you running Scaffold-Eth?

**Comment by chris13524** [comment]
@codenamejason I think the issue is that .devcontainer.json is designed for Codespaces only? I'm using the remote containers VS Code extension: https://code.visualstudio.com/docs/remote/containers

**Comment by codenamejason** [comment]
This is kind of new territory for Scaffold-Eth using the Codespaces container... will have to investigate how to rectify without reverting the previous PR.
