### ISSUE TITLE
Need Help: Unable to submit any challenge on speedrunethereum

### ISSUE THREAD

**Issue by numboDumbo** [scaffold-eth/scaffold-eth#812]
Hi, I am unable to submit any challenge. After entering the Surge URL and Etherscan URL, the page waits endlessly to submit. 
I am using Rinkeby. Can I get some logs or any way to debug this?

**Comment by carletex** [comment]
Hi @numboDumbo 

Can you provide some screenshots? (UI and console errors). A video will be perfect :)

Are you signing the challenge submission with metamask... or it doesn't even reach to that point?

Thanks!
