### ISSUE TITLE
yarn commands not working

### ISSUE THREAD

**Issue by hoysal08** [scaffold-eth/scaffold-eth#815]
i am very new the scaffold-eth setup, i am stuck here because none of my yarn commands seems to work.
![Screenshot (157)](https://user-images.githubusercontent.com/78635921/177044139-7250fc54-e726-4c65-915f-cd032ed007ad.png)
![Screenshot (156)](https://user-images.githubusercontent.com/78635921/177044141-34b388fa-5f8e-4fa7-a561-f7b0de0df101.png)

**Comment by codenamejason** [comment]
Your screenshots don't show anything... can you grab any errors you may be getting @hoysal08
