### ISSUE TITLE
scaffold-eth challenges challenge-2-token-vendor

### ISSUE THREAD

**Issue by issawayzani** [scaffold-eth/scaffold-eth#846]
hello, i started with the steps to open challenge-2-token-vendor file that is found in speed run ethereum. 
after yarn deploy i have these 2 errors that i coudnt solve .i saw that you need to put yarn chain before yarn start but i did it and i have the same error.
Unhandled Rejection (Error): missing response (requestBody="{\"method\":\"eth_accounts\",\"params\":[],\"id\":42,\"jsonrpc\":\"2.0\"}", requestMethod="POST", serverError={}, url="http://3000-scaffoldeth-scaffoldeth-zzclhoz6pbk.ws-eu59.gitpod.io:8545", code=SERVER_ERROR, version=web/5.4.0)

Unhandled Rejection (Error): could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.4.1)

**Comment by codenamejason** [comment]
I believe this has to do with running via Gitpod and we are looking into it.

**Comment by codenamejason** [comment]
closing this for now, reopen in the challenges repo if you continue to have issues.
