### ISSUE TITLE
project id required

### ISSUE THREAD

**Issue by christopheragnus** [scaffold-eth/scaffold-eth#847]
Hi there,

I have deployed my contract and `yarn start` in the frontend. But when I try to `mint nft`, I get the following error:

`Unhandled Rejection (HTTPError): project id required`

Stack frame: https://i.imgur.com/wyCm1zK.png

How do I fix this?

**Comment by codenamejason** [comment]
Your image link is not working, try uploading using this vvvv below.

**Comment by EngrGord** [comment]
This error usually arises when infura ID is invalid or you don't change the infura ID on both hardhat,config.js and constants,js

**Comment by codenamejason** [comment]
Yes, update the Infura ID and alchemy key

**Comment by codenamejason** [comment]
@christopheragnus I believe this is due to the IPFS changes when calling api you need auth from infura project id. See here https://github.com/scaffold-eth/scaffold-eth-challenges/tree/challenge-0-simple-nft the code has been updated to accommodate these changes.

**Comment by codenamejason** [comment]
closing this
