### ISSUE TITLE
Broken multi-sig link in README

### ISSUE THREAD

**Issue by samajammin** [scaffold-eth/scaffold-eth#849]
The "👩‍👩‍👧‍👧 Build a multi-sig that uses off-chain signatures" link is broken:
https://github.com/scaffold-eth/scaffold-eth/tree/meta-multi-sig

What's the correct branch for the multi-sig?

Thanks!

**Comment by samajammin** [comment]
Is it https://github.com/scaffold-eth/scaffold-eth/tree/challenge-3-multi-sig ?

**Comment by samajammin** [comment]
Or maybe https://github.com/scaffold-eth/scaffold-eth-examples/tree/streaming-meta-multi-sig ?

**Comment by codenamejason** [comment]
https://github.com/scaffold-eth/scaffold-eth-challenges/tree/challenge-5-multi-sig
