### ISSUE TITLE
getting error while running yarn chain

### ISSUE THREAD

**Issue by SigireddyBalasai** [scaffold-eth/scaffold-eth#858]
![Screenshot 2022-08-20 171531](https://user-images.githubusercontent.com/101649913/185744465-66b6b733-ad9a-4b9d-8d92-43c4b9c96918.png)

**Comment by ayushtyagi14** [comment]
Getting the same error! Did you find how to resolve it?

**Comment by SigireddyBalasai** [comment]
no bro

**Comment by codenamejason** [comment]
Need more info.. what directory are you in? is it root? @SigireddyBalasai

**Comment by vivinvinh212** [comment]
@ayushtyagi14 @SigireddyBalasai You guys probably using NodeJS with version >= 17 and they have some problem with open SSL legacy. Uninstall them and install NodeJS <= 16.17 from the NodeJS website. That would help.

**Comment by codenamejason** [comment]
Are you still having issues @SigireddyBalasai @ayushtyagi14
