### ISSUE TITLE
ipfs-image-upload branch is broken

### ISSUE THREAD

**Issue by gotnoshoeson** [scaffold-eth/scaffold-eth#870]
Proposing a new branch.

I had a few issues with the ipfs-image-upload branch. To start, couldn’t yarn install. Infura recently added authentication for access to IPFS, so I added that bit. I removed the Amazon S3 uploading method. Modified the frontend a bit to work with my changes. Authentication is currently being read from .env. There is a warning in the README that this is not secure for a public deployed frontend. Next step I’d like to set the branch up to use a serverless function with Vercel to safely deploy app and secure auth credentials. In my fork I have the branch named as “ipfs-auth”.

**Comment by codenamejason** [comment]
sounds good @gotnoshoeson look forward to the PR 🥳

**Comment by gotnoshoeson** [comment]
I submitted a pull request. Yeah I'm still able to help out with this. Last message I saw was that the pull request was closed. I think I tried to add a new branch because I didn't include the AWS option. Does anyone really want to use AWS for decentralized mindset moving forward?
