### ISSUE TITLE
[Quest] Sensible defaults for RPC Requests

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/scaffold-eth#882]
On a fresh install, scaffold-eth makes around 50/80 RPC requests per minute. This causes that most of the deployed scaffold-eth builds suffer from RPC errors (due to limits).

**Issue:** We are setting multiple providers & using hooks that make requests on each block (useOnBlock, useBalance, etc).

I think it's fine if someone want on-block updates, but shouldn't be the default.

Some updates that we could make:
- Having a default **polling time** (like 5000ms) that is passed to every hook that accepts a pollTime.
- **LocalProvider vs MainnetProvider**: If localProvider points to Mainnet, we don't need to have two providers (modify useStaticJsonRPC hook to accept a localProvider as an argument => if mainnet, return localProvider. If not, instantiate new provider.
- Comment out useOnBlock hook.

Maybe we can omit some of these if we are working on localhost (so we have a more instant feedback)

**Comment by supernovahs** [comment]
Do we  have any data through which we know how much requests are coming from localhost vs Production?
