### ISSUE TITLE
Main website url is not working

### ISSUE THREAD

**Issue by jeremyjs** [scaffold-eth/scaffold-eth#885]
Navigating to https://scaffoldeth.io/ gives this error message in Google Chrome:

Instead maybe it can just redirect to https://docs.scaffoldeth.io/ which seems to be working fine.

![Screen Shot 2022-09-15 at 19 16 30](https://user-images.githubusercontent.com/2359092/190542111-48c10bee-42f6-4872-b09b-9e0682bf0a04.png)

**Comment by codenamejason** [comment]
Correct, you have to use http://scaffoldeth.io and it just redirects you to the Github repo. @jeremyjs
