### ISSUE TITLE
Yarn cannot run for this project

### ISSUE THREAD

**Issue by Lisanaaa** [scaffold-eth/scaffold-eth#900]
Hi, I am running this project in root path, but encounter problems: `Internal Error: @scaffold-eth/monorepo@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile`, the interested thing is that we have `private` set to `true` in root `package.json`. 

My Node.js version is 16.x, Yarn version is 3.2.3,
![image](https://user-images.githubusercontent.com/28261876/193839438-0b84564f-e6ed-4adb-854d-676288c9240b.png)
![image](https://user-images.githubusercontent.com/28261876/193839519-3f93303b-3003-4c70-a172-4b95e7a71b18.png)

**Comment by byeweb2** [comment]
I have almost the same problem `yarn install` or `yarn chain` not working:
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'chain'

**Comment by byeweb2** [comment]
For Debian users, I solve it by:
https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install

**Comment by codenamejason** [comment]
I believe this is the `yarn` version being 3.x and Scaffold-Eth uses 1.x @Lisanaaa @byeweb2 I just merged a PR that shows what version you need this morning.
