### ISSUE TITLE
Develop a bot

### ISSUE THREAD

**Issue by KUNTA97** [scaffold-eth/scaffold-eth#909]
Can you develop a specific bot?

**Comment by RICHWAYS** [comment]
> Can you develop a specific bot?
Yes

**Comment by KUNTA97** [comment]
How can i contact you? RICHWAYS

**Comment by KUNTA97** [comment]
> > Can you develop a specific bot?
> Yes 
> 

How can I contact you

**Comment by KUNTA97** [comment]
> > Can you develop a specific bot?
> Yes 
> 

KUNTA-KINTE#7306 DM me on discord dude
