### ISSUE TITLE
Issue with yarn start

### ISSUE THREAD

**Issue by harrychaklader** [scaffold-eth/scaffold-eth#921]
start and build function in package.json dont seem to work.

**Comment by codenamejason** [comment]
@harrychaklader have you been able to solve your issue? Try to give more context if you can, ie: screenshots, code examples, etc.. There are multiple `package.json` files in the project repo (it is a monorepo setup), the root `package.json` just references the others.

**Comment by mblaw1011** [comment]
![image](https://user-images.githubusercontent.com/57417892/204745127-5e0e6f7d-1f8d-4558-bec6-6b510848aaab.png)
![image](https://user-images.githubusercontent.com/57417892/204745370-df1050d5-9d45-4263-b35a-d63f3996055d.png)

It  show this error after i run yarn start

**Comment by Azizadx** [comment]
> ![image](https://user-images.githubusercontent.com/57417892/204745127-5e0e6f7d-1f8d-4558-bec6-6b510848aaab.png) ![image](https://user-images.githubusercontent.com/57417892/204745370-df1050d5-9d45-4263-b35a-d63f3996055d.png)
> 
> It show this error after i run yarn start

use this cmd 
`export NODE_OPTIONS=--openssl-legacy-provider`

**Comment by harrychaklader** [comment]
In your package.json go to your "scripts" section and change the start and build commands.

`"start":` "react-scripts --openssl-legacy-provider start",
    "build": "react-scripts --openssl-legacy-provider `build"`

this should be what you change them to, not sure if running export NODE_OPTIONS=--openssl-legacy-provider will help or not, but I got mine to work by switching the package.json scripts.

**Comment by Azizadx** [comment]
> In your package.json go to your "scripts" section and change the start and build commands.
> 
> `` "start":` "react-scripts --openssl-legacy-provider start", "build": "react-scripts --openssl-legacy-provider `build" ``
> 
> this should be what you change them to, not sure if running export NODE_OPTIONS=--openssl-legacy-provider will help or not, but I got mine to work by switching the package.json scripts.

yeah this one is a better approach then mine you need to run it every time you restart the terminal window 
@mblaw1011 I recommend this
