### ISSUE TITLE
Many 'deprecated' warnings with yarn install

### ISSUE THREAD

**Issue by walkerlj0** [scaffold-eth/scaffold-eth#986]
I tried installing & using the yarn-chain command (forked Mar 3), but got a lot of errors about deprecated packages and `yarn chain` was unsuccessful. See images:

 
![Screenshot 2023-03-03 at 9 40 12 AM](https://user-images.githubusercontent.com/66978602/222777257-a1692edf-50d8-4db8-bd7b-7daa30dbddf9.png)
![Screenshot 2023-03-03 at 9 40 26 AM](https://user-images.githubusercontent.com/66978602/222777283-5bc5101c-0e92-4f41-ad6d-5578d01f86a8.png)
![Screenshot 2023-03-03 at 9 40 12 AM](https://user-images.githubusercontent.com/66978602/222777339-30292464-610d-43a7-8dcb-10b534ebb3ba.png)

**Comment by cotoneum** [comment]
same

**Comment by cotoneum** [comment]
should try changing yarn version to v1 from v3
